import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    
    in property <string> results: "";
    in property <string> current-formula: "Fahrenheit to Celsius";
    in property <string> input-placeholder: "F";
    in property <string> window-title: "Fahrenheit to Celsius Converter";

    callback convert-fahrenheit(string);

    callback change-formula();

    background: #313e50;

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row{
            Text {
                text: root.window-title;
                horizontal-alignment: center;
                font-size: 30px;
                font-weight: 900;
            }
        }
        Row{
            input := LineEdit {
                font-size: 16px;
                placeholder-text: root.input-placeholder;
            }
        }
        Row{
            Button{
                text: root.current-formula;
                clicked => {
                    change-formula()
                }
            }
        }
        Row{
            Button {
                text: "Calculate";
                clicked => {
                    convert-fahrenheit(input.text)
                }
            }
        }
        Row{
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
